### ISSUE TITLE
impossible to scroll the dialogue list

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#102]
**Describe the bug**
It is impossible the dialogue list on some mobiles. When the screen is touched to swipe up or down, the app opens the according dialogue instead of recognising the swipe gesture. 

**To Reproduce**
1. open dialogue list on a mobile
2. swipe on the mobile screen in order to scroll the list down or up
3. scrolling is not recognised.

**Comment by ozFri** [comment]
Fixed, thank you
