### ISSUE TITLE
event based tutorial

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#103]
**Is your feature request related to a problem? Please describe.**
The current tutorial is not accepted by the users. Most users have a trial and error approach to learn new software. They don't want to be taught the whole process, they are looking for what next to do. 

**Describe the solution you'd like**

When the user is logged in, the app checks for a cookie indicating the user has already been shown the tutorial. 

If the user open the main screen and no cookie is found, the following message is shown centrally: "Chose which topic you want to discuss". If the users clicks the "OK" button (bottom right), the message is closed. If the user clicks "skip tutorial" (bottom left), the message is closed and a cookie is set.  

If the user opens a topic and no cookie is found, the following message is shown: "Publish your opinion, to discuss it with others". (Optional: the pencil icon is highlighted/brightly coloured.) If the users clicks the "OK" button, the message is closed.

If the user published an opinion (and no cookie is found), the following message is shown: "Chose the opinion you want to discuss". OK closes the message. 

If the user requested a dialogue (and no cookie is found), the following message is shown: "You can find your dialogues here". Dialogue list icon is highlighted/brightly coloured. "OK" closes the message

If the user has an active dialogue (+ no cookie), the following message is shown "Congratulations! You are now having your first chat. Use the slider to show how you like the dialogue. Your rating will determine the colour of the line connecting both of your opinions. "Let's go" closes the message and sets a cookie.

**Comment by ozFri** [comment]
Some purely technical notes:
I'm using the library [Driver.js](https://kamranahmed.info/driver.js/) for the guided tour.
Will try to use [this trick](https://www.babylonjs-playground.com/#7PKR9H#0) to inform the tour on the positions of the non-html elements that we need to highlight.
The default driver.js box is pretty bland, as shown in the demo, but it can be easily styled via CSS.

**Comment by avirankatzsofi** [comment]
Done.
https://demo.dpt.world has been updated to include this feature.
