### ISSUE TITLE
create 3 new opinions to create 1 new topic 

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#27]
**Is your feature request related to a problem? Please describe.**
The quality of our topics is key to attracting interesting discussions. At the moment some users treat topics in a "I was here" manner. They might create topics without real intention to discuss with others. 

**Describe the solution you'd like**
the "create new topic" button would have a counter that is raised 1/3 with every opinion they users creates. If the counter is 0, the button should be (visibly and technically) disabled. 

If users feel they have to earn the right to open new discourses by participating in existing discourses, they might create much better topics by exploring the existing discourses first.

**Comment by Iwan-Ittermann** [comment]
related to https://github.com/digital-peace-talks/DPT/issues/63

**Comment by galorpaz** [comment]
Hi Iwan, as I see we should not remove the button completely, as asked in #63. Instead we should just hide it, and make it visible only when user earned 1 point?

**Comment by Iwan-Ittermann** [comment]
sorry! this issue is outdated. It is not included in the work list though. Still there shouldn't be contradicting issues. We could implement this feature (to allow user topic generation) much later in the process, once the chat, rating and visualization parts are working fine.
