### ISSUE TITLE
show "you don't have any dialogues yet" when dialogue list is empty

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#30]
**Is your feature request related to a problem? Please describe.**
Users with no dialogues receive an empty dialogue list, with no clue what this could be. 

**Describe the solution you'd like**
There could be a welcoming message like "You don't have any dialogues yet. Choose a topic and publish your opinion to request dialogues with other opinions."

**Describe alternatives you've considered**
The tutorial would provide similar information, yet it might be skipped or users don't fully process it. 

**Additional context**
Its very common for webmail services to display message ("you have no messages at the moment") when inbox has no mails.

**Comment by avirankatzsofi** [comment]
Fixed in c4778f2
