### ISSUE TITLE
bottom-menu, dialog-frame, some other frames: have to use desktop estate - respectively have to become wider.

### ISSUE THREAD

**Issue by MartinDPT** [digital-peace-talks/DPT#32]
**Is your feature request related to a problem? Please describe.**
expand UX by expanding the UI ;) 

**Describe the solution you'd like**
600px in desktop-mode for menu and most userinterfaces should solve the problem

**Describe alternatives you've considered**
or keep it like it is

**Additional context**
i am open for creative, constructive solutions!

**Comment by Iwan-Ittermann** [comment]
the problem statement is not valid. 

Where is UX hindered? Do you think the menus are too small?
