### ISSUE TITLE
fixing the layout of the finished and published dialogue-outcome/dialogue-conclusion

### ISSUE THREAD

**Issue by MartinDPT** [digital-peace-talks/DPT#35]
**Is your feature request related to a problem? Please describe.**
i've to go over this... will take some blood, sweat and tears.

**Describe the solution you'd like**
this has to become a "setcard" of past dialogues between two people you don't know: easy to read, informative, simple but sexy.

**Describe alternatives you've considered**
there is no alternative! D:

**Additional context**
Could be that this needs some backend-shifting.
Happy to hear/read some constructive input!

**Comment by Iwan-Ittermann** [comment]
The description is quite sloppy, could you be more precise and less funny in your descriptions?

**Comment by Iwan-Ittermann** [comment]
I don't understand what the issue is about.

**Comment by MartinDPT** [comment]
maybe this is the same but different issue: "pack closed dialogue away in a folded list #28 "
