### ISSUE TITLE
topics get bigger if the have more opinions

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#37]
**Is your feature request related to a problem? Please describe.**
The topic level gets cluttered quite fast. Users don't see, which topics are relevant. 

**Describe the solution you'd like**
topic font size is correlated to number of opinions. 

**Describe alternatives you've considered**
displaying the number of opinions behind the topic requires the user to zoom to the topic and read it. This is not as efficient information as if he does not need to read but can grasp from fare. 

**Additional context**
Clustering would increase topic discovery exponentially. Still correlating topic size with amount of opinion would work complementary to clustering

**Comment by MartinDPT** [comment]
we can´t do it by font-size right now. (to many variables) only by scaling the size of the afterwards  rendered "pic" ... this leads to smaller but different problems. this enhancement needs a lot of refracturing to the status quo. 
PS: my babylon-example back in july did the same thing. circle-clusters around topics, growing by the number of opinions inside each topic. (back then with random numbers) *smile*
