### ISSUE TITLE
Revise the dialog module

### ISSUE THREAD

**Issue by Metin74** [digital-peace-talks/DPT#4]
**Is your feature request related to a problem? Please describe.**
Adjustments, improvements to the Dialo module are necessary to customize the appearance of different output devices.

**Describe the solution you'd like**
Text fields, text size, icons and buttons should be adjusted.

**Describe alternatives you've considered**

**Additional context**
New icons would be nice.

**Comment by MartinDPT** [comment]
Done! I need feedback asap!
