### ISSUE TITLE
Integrate button to request dialogue into opinion context

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#58]
**Is your feature request related to a problem? Please describe.**
All of our buttons are located in the GUI, except one: the one to request a dialogue. 

User test showed, that people have great difficulties to identify this key element. They click on the opinions it self but fail to identify the small icon next to the opinion. 

**Describe the solution you'd like**
At the moment clicking on an opinion opens the opinions context frame. 
The "request dialogue" button (or a note that you can not request/propose a dialogue until you published your own opinion) should be moved here.   

**Describe alternatives you've considered**
In case someone did not publish his opinion yet and opens the context frame, I thought about integrating the "create new opinion" button. But this could people to write a reply instead of an original opinion.

**Comment by Iwan-Ittermann** [comment]
This issue requires graphic design. @ozFri

**Comment by avirankatzsofi** [comment]
done in a8803ee.
Screenshot of current implementation:

![image](https://user-images.githubusercontent.com/42338902/77740907-1c5a4400-7025-11ea-820c-04a83869b7b1.png)
