### ISSUE TITLE
redesign "finish dialogue" button

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#60]
**Is your feature request related to a problem? Please describe.**
The "finish dialogue" button is crucial to our concept. Yet it is very rarely used. 
Users don't understand why they should finish a dialogue, if they could simply leave it open (as they are used from any other messenger). 

**Describe the solution you'd like**
The finish dialogue could be redesigned and repositioned to look like the "hang up" icon widely know from mobile phones. 

![image](https://user-images.githubusercontent.com/40490654/72071016-25bbf600-32eb-11ea-97ae-2b13fb078055.png)

**Comment by Iwan-Ittermann** [comment]
This could be even better: framing the end as "LEAVING" 
many users had to leave a group chat because it was annoying. That's a strong analogy we can use. 

Example icon:
https://www.google.de/url?sa=i&url=https%3A%2F%2Fthenounproject.com%2Fterm%2Fleave%2F565717%2F&psig=AOvVaw2EKVneIn1Y5P-V92iSqUEo&ust=1580894219907000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPi-147It-cCFQAAAAAdAAAAABAD

**Comment by Iwan-Ittermann** [comment]
@ozFri this issue requires graphic design

**Comment by ozFri** [comment]
I suggest using a finish flag a.k.a checkered flag,
And adding a text like:
"I feel like we've talked enough, let's finish this conversation"
![noun_checkered flag_1423985](https://user-images.githubusercontent.com/1573884/77861689-13cd5d80-721f-11ea-934a-ca72f2b03f48.png)

**Comment by Iwan-Ittermann** [comment]
the icon is meant to serve for angry ends. As a quit/block button, if a personal boundary is overstepped. It's the evolution of the crisis button. In a later version, we might link it to a crisis mode, where we try to prevent the angry ending..

**Comment by Iwan-Ittermann** [comment]
I do think though, that the flag is a really good symbol and it will come back somehow somewhat!

**Comment by avirankatzsofi** [comment]
Redesigned, screenshot below. I also uploaded this version https://demo.dpt.world
@Iwan-Ittermann I'm not closing this issue yet, waiting for your approval first.
![image](https://user-images.githubusercontent.com/42338902/78470378-bd39b500-7731-11ea-95d0-7de3a55fb565.png)

**Comment by Iwan-Ittermann** [comment]
As discussed: please name the button "Quit and give rating"

**Comment by avirankatzsofi** [comment]
Maybe "Quit and rate dialog" instead?
