### ISSUE TITLE
apply red/green/blue color to lines, depending on rating score

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#64]
**Is your feature request related to a problem? Please describe.**
the color of the lines should represented the level of respectfulness of the given dialogue. 

**Describe the solution you'd like**
If I click on "finish dialogue" I am presented with three scales to rate.
The scales are titled: 
- How well did we explore our own perspectives?
- How well did we explore other perspectives? 
- How well did we back our claims? 

I can chose a value from 0 to 100 for each scale. 
The values of both ratings are added up. If the total is 0 - 350, the line is colored red. If the total is 351 - 450, the line is colored blue. If the total is 450+, the line is green.

**Comment by avirankatzsofi** [comment]
The 1hr estimation was for the original description (green + red = blue), with the existing rating mechanism. A new, points based mechanism will take about 5 hrs.

**Comment by Iwan-Ittermann** [comment]
yes. lets go with the extra hours.

**Comment by avirankatzsofi** [comment]
> **Is your feature request related to a problem? Please describe.**
> the color of the lines should represented the level of respectfulness of the given dialogue.
> 
> **Describe the solution you'd like**
> If I click on "finish dialogue" I am presented with three scales to rate.
> The scales are titled:
> 
> * How well did we explore our own perspectives?
> * How well did we explore other perspectives?
> * How well did we back our claims?
> 
> I can chose a value from 0 to 100 for each scale.
> The values of both ratings are added up. If the total is 0 - 350, the line is colored red. If the total is 351 - 450, the line is colored blue. If the total is 450+, the line is green.

Just asking for clarification - a dialog may receive a rating between 0 and 300 from each participant, so it's final score would be 0 - 600. Am I getting it right?

**Comment by Iwan-Ittermann** [comment]
> Just asking for clarification - a dialog may receive a rating between 0 and 300 from each participant, so its final score would be on a scale from 0 to 600. Am I getting this right?
yes, 0 to 600 in total.

**Comment by avirankatzsofi** [comment]
After starting to work on this issue, I understand that we're going to have a compatibility issue:
Existing dialogs have a rating between `0..1` from each participant, and so all of them are going to be painted red. I wanted to discuss that with you, and decide on a course of action.
- If the existing data in the demo+corona instances doesn't matter, we can reset their DBs and that's all it takes.
- If the data in those instances is important, then we should probably use the following rating mechanism: 
  1. Mean value calculation from the 3 sliders for each participant (which will result in `0..1`).
  2. Color the lines based on a second mean value, of the final rating from each participant: `0..0.58`=red (350/600=0.58); `0.58..2/3`=blue; `2/3..1`=green

**Comment by avirankatzsofi** [comment]
Implemented using the existing scale (`-1..1`), in order to implement without harming the corona instance.

![image](https://user-images.githubusercontent.com/42338902/79227237-42c31080-7e68-11ea-88b6-7c9bc8c45765.png)

**Comment by avirankatzsofi** [comment]
Done, uploaded to the demo instance

**Comment by avirankatzsofi** [comment]
Reopening to fix small screens issue

**Comment by avirankatzsofi** [comment]
Quick fix in 3688673 (not 100% bulletproof but I think that it would do for now).
Closing for now, @Iwan-Ittermann feel free to check demo.dpt.world and reopen this issue if needed.
