### ISSUE TITLE
make conclusion optional

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#65]
**Is your feature request related to a problem? Please describe.**
Users need to write a conclusion in order to finish and rate a dialogue. Forcing the input will create lots of noise from people that don't know what to write. 

**Describe the solution you'd like**
users can finish and rate dialogues without submitting a conclusion

**Comment by avirankatzsofi** [comment]
@Iwan-Ittermann Oz suggested a quick fix - setting "no reason provided" as the default reason. If you approve, we can merge #96

**Comment by Iwan-Ittermann** [comment]
yes, sounds good, how about inserting "please enter a reason (optional)" as
default.. ?

**Comment by avirankatzsofi** [comment]
> yes, sounds good, how about inserting "please enter a reason (optional)" as default.. ?

Possible but will surely take more time than the suggested one, as it must involve some change in the app logic (e.g. disabling "last statement: ..."), whereas a default reason does not.
In terms of time estimation, default reason took @ozFri 20 minutes (we won't charge for it if it's not implemented), and the optional reason would probably be around 1-2 hrs.

**Comment by ozFri** [comment]
I can add a placeholder text with this hint, I think that was Iwan's intent.

**Comment by ozFri** [comment]
Added placeholder text,
Placeholder text vanishes as the user starts typing,
If the user didn't enter text "No reason provided" is recorded
see screenshots:

![Screenshot_2020-04-13_19-28-46](https://user-images.githubusercontent.com/1573884/79138363-10100e00-7dbd-11ea-8767-b307d9d41f77.png)
![Screenshot_2020-04-13_19-28-22](https://user-images.githubusercontent.com/1573884/79138368-11d9d180-7dbd-11ea-8382-0ec22e79bbc1.png)
![Screenshot_2020-04-13_19-27-16](https://user-images.githubusercontent.com/1573884/79138369-12726800-7dbd-11ea-9038-e93e794e2b02.png)

**Comment by Iwan-Ittermann** [comment]
top!
