### ISSUE TITLE
new login page

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#70]
**Is your feature request related to a problem? Please describe.**
The login page is totally overloaded. _User_ want to _use_ the app, not read about it. 

**Describe the solution you'd like**
The layout and text is redone. 

If the user opens the page and he did not log out the last time, he is taken straight to the main screen. 

If a logged in user logs out, he is taken to the login page. 

**Additional context**
Sketch
![new login screen](https://user-images.githubusercontent.com/40490654/73473052-5e9c3780-438c-11ea-940e-251d73348d22.png)

There could be a button to create a new random passphrase, so users can choose a nice one.

**Comment by avirankatzsofi** [comment]
Completed in c4778f2.
Alive at https://demo.dpt.world

**Comment by Iwan-Ittermann** [comment]
- please emphasise the sentence "the passphrase cannot be recovered"
- please change the paragraph in the footer to "Please be aware that DPT grants everyone the chance to voice their opinion. Even if it's, within the boundaries of the German federal law, radical. Nobody, on the other hand, will ever be allowed to cross your personal boundary (1 strike policy) in DPT."

**Comment by avirankatzsofi** [comment]
Textual changes implemented and are visible at demo.dpt.world
