### ISSUE TITLE
separate logout button

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#71]
**Is your feature request related to a problem? Please describe.**
The logout button is hidden under menu>settings. users that want to protect their privacy might not find it. 

**Describe the solution you'd like**
 logout icon is placed in the the lower right(?) corner. If it is clicked, the same text and "copy to clipboard" button is shown, but in a separate window. 
Also a "download as .txt" button is shown (see dpt.soficoop.com). 
At the button of the window the user can click "cancel" or "yes, log me out"

**Comment by ozFri** [comment]
#77

**Comment by Iwan-Ittermann** [comment]
@ozFri this issue requires graphic and UX design
