### ISSUE TITLE
explain controls in tiny fonts

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#74]
**Is your feature request related to a problem? Please describe.**
navigating the camera in 3D is difficult and not all intuitive. 

**Describe the solution you'd like**
A text in tiny font size, that is permanently shown. It explains three necessary controls.

**Describe alternatives you've considered**
The tutorial/guided tour could explain controls _and_ features, but that is too much memory load. Also the controls are something you need to do a couple of times in order to internalize. 

Example attached
![controls explained](https://user-images.githubusercontent.com/40490654/73642849-bbd90700-4672-11ea-818c-9e783867efdf.png)

**Comment by avirankatzsofi** [comment]
Is this different than the current onboarding tour?

**Comment by Iwan-Ittermann** [comment]
The camera controls should always be present. The onboarding tour should in future focus on explaining the principle of choosing a topic, posting your opinion and requesting a chat. 

Another example: 
![image](https://user-images.githubusercontent.com/40490654/77521063-648d3100-6e82-11ea-8feb-ec1c136ad899.png)

**Comment by Iwan-Ittermann** [comment]
> Describe alternatives you've considered
The tutorial/guided tour could explain controls and features, but that is too much memory load. Also the controls are something you need to do a couple of times in order to internalize.

**Comment by ozFri** [comment]
![Screenshot_2020-04-10_05-14-13](https://user-images.githubusercontent.com/1573884/78956246-59750a80-7aea-11ea-90bf-73d02d53f361.png)
What do you think about this helper window?

**Comment by Iwan-Ittermann** [comment]
The text should be in Markazi Regular, please. (Ci attached)
Is there a way to show different controls depending if its a mobile or desktop device?
In any case, the text can be shortened using a table:

**Comment by ozFri** [comment]
![Screenshot_2020-04-11_22-16-48](https://user-images.githubusercontent.com/1573884/79052912-4bd29880-7c42-11ea-972d-9c6e5b04e445.png)
New version

**Comment by Iwan-Ittermann** [comment]
sweet, please use transparent background, then we can close it.

**Comment by avirankatzsofi** [comment]
Fixed in #92 
@Iwan-Ittermann you can see the changes at demo.dpt.world. Feel free to reopen if needed.

**Comment by ozFri** [comment]
Suggestion for improvement:
On mobile- only show Touch explanation.
Also- instead of writing Desktop and Mobile we can write Mouse and Touch, Touch can also be relevant to some laptops/desktops with touchscreen.

**Comment by avirankatzsofi** [comment]
The ability to minimize the controls explanation should be implemented, as this takes much of the screen space on smaller screens.

**Comment by ozFri** [comment]
I've added a compact mobile view for smaller screens, 
I hope this solution is ok.
If minimizing is preferred I will fix it, as I might have misinterpreted the requirement. 
Otherwise we can close the issue.

Screenshot for phone, tablet and laptop:

![Screen Shot 2020-04-16 at 13 44 20](https://user-images.githubusercontent.com/1573884/79447445-86dd1f00-7fe8-11ea-8c9f-412b89167f85.png)
![Screen Shot 2020-04-16 at 13 43 07](https://user-images.githubusercontent.com/1573884/79447451-88a6e280-7fe8-11ea-9d87-9e9d88044f8d.png)
![Screen Shot 2020-04-16 at 13 42 55](https://user-images.githubusercontent.com/1573884/79447452-893f7900-7fe8-11ea-85db-46f723891673.png)
