### ISSUE TITLE
remove text in proposition

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#76]
**Is your feature request related to a problem? Please describe.**
The proposition can be used to verbally abuse other users based on their opinion. 

**Describe the solution you'd like**
The form "please enter your proposition" is changed into offering two buttons: "request dialogue" and "cancel"["never mind"]

**Describe alternatives you've considered**
Implementing a filter that shows only requests that meet the users self-determinate requirements. As this is fare more complex, we need to remove the proposition at least for now, until we have a safe alternative.

**Comment by Iwan-Ittermann** [comment]
This has implication for the dialogue list. Instead of the proposition text, the dialogue list could show the opinion of the requester/proposer.

**Comment by avirankatzsofi** [comment]
This results in an undesired side effect (with #58) as the following scenario applies:

1. The user clicks an opinion
2. Opinion context appears
3. The user clicks "request dialog"
4. Proposition context appears. The user has two options: "request dialog" and "never mind"

I suggest the following solution:

A click on a dialog icon opens the opinion context, just like a click on the opinion text. When "request dialog" is clicked in the opinion context, a dialog is suggested without any textual proposition.

@Iwan-Ittermann @ozFri what do you think?

**Comment by Iwan-Ittermann** [comment]
@avirankatzsofi I see what you mean and agree with it. 

Would the following solution add much extra effort? 

1. the dialogue icon is removed (why to have two elements with the same function?)
2. Opinion context shows
- If I did not publish my opinion: "Want to have a dialogue with this opinion? Please publish your own opinion first." 
- If I did publish my opinion: "request dialogue" button is shown.

**Comment by avirankatzsofi** [comment]
No problem.
We'll create a separate issue for the section below (it's the only one that not implemented yet). is that ok?
> * If I did not publish my opinion: "Want to have a dialogue with this opinion? Please publish your own opinion first."

**Comment by Iwan-Ittermann** [comment]
yes, that's fine

**Comment by Iwan-Ittermann** [comment]
could you also copy paste the create new opinion button into the opinion context, if the user did not publish his own opinion yet?

**Comment by avirankatzsofi** [comment]
Fixed, visible at https://demo.dpt.world
