### ISSUE TITLE
disable(modify?) guide tour 

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#87]
if the controls are shown and a link to [the tutorial](https://medium.com/@IwanIttermann/what-are-the-digital-peace-talks-and-how-do-i-use-them-fbd33efd26e9) is supplied , we have less damage, if we do without the guide tour.

**Comment by ozFri** [comment]
Estimating this as 1-2 hours work.

**Comment by Metin74** [comment]
aoutsch

**Comment by Iwan-Ittermann** [comment]
would changing the content and the measures, so the guided tour/tutorial gets much shorter and the frame a bit smaller be same or less effort?

**Comment by avirankatzsofi** [comment]
I think that it would be around the same effort.
I'd like to explain the given estimate - we have to take into account all of the things that could break and will need to be fixed. So just removing the html code is probably not enough, as this will probably require some change in the app logic (e.g. removing the cookie logic etc).

**Comment by Iwan-Ittermann** [comment]
Just to elaborate: If the tour stays and is just made much shorter, wouldn't that mean much less potential breaks?

**Comment by ozFri** [comment]
I've removed the parts about navigation from the tour, and made it smaller.
This is a quick fix for now, but if we want to continue working on it, it needs to be done in a more orderly way, so Aviran was right, both tasks are eventually around the same amount of work.

**Comment by ozFri** [comment]
![2020-04-16 03-34-22 832028348](https://user-images.githubusercontent.com/1573884/79405578-7d7a9500-7f9d-11ea-8a55-4527d84b10ae.gif)

**Comment by avirankatzsofi** [comment]
@Iwan-Ittermann are there any other slides that need to be removed as well?

**Comment by Iwan-Ittermann** [comment]
maybe the icon for "create new opinion" could be updated, but else from
that the quick fix is cool.

**Comment by Iwan-Ittermann** [comment]
Could you please change the content as follows:
[No more headlines, white fonts for body text[
1. box: How to use DPT
2.box:  Choose a topic
3. box: Write your opinion. [pencil icon]
4. box: Click on opinions you want to chat with (scroll down!)
5. box: Click "quit and rate" to publish a chat.

**Comment by avirankatzsofi** [comment]
@Iwan-Ittermann We're on it

**Comment by ozFri** [comment]
![2020-04-20 04-28-06 410843228](https://user-images.githubusercontent.com/1573884/79705808-a1044f00-82bf-11ea-9258-9273c51efe85.gif)

**Comment by ozFri** [comment]
![2020-04-20 04-32-35 964890559](https://user-images.githubusercontent.com/1573884/79705931-1112d500-82c0-11ea-87ba-f0b4af0d1118.gif)
New slides, please approve

**Comment by ozFri** [comment]
![2020-04-20 04-34-28 257232250](https://user-images.githubusercontent.com/1573884/79706009-5d5e1500-82c0-11ea-9226-31e96eadf2a9.gif)
New slides, please approve
Sorry if you're getting multiple emails, delted previous versions of gif

**Comment by Iwan-Ittermann** [comment]
Hi, please remove png in slide 2 and 4 (just text)

New text for slide 4: 
Click on an opinion to request a dialogue.

Please delete slide 5.

**Comment by avirankatzsofi** [comment]
Done in #99 
@Iwan-Ittermann you can check it out at https://demo.dpt.world
If approved, we will update the corona instance
